name: Testing Secrets

on:
  # Write the event triggering the workflow
  pull_request:
    branches: master

jobs:
  print_secrets:
    runs-on: ubuntu-latest
    
    permissions:
      # Grant the write permissions
      pull-requests: write

    steps:
      - name: Comment on Pull Request
        uses: thollander/actions-comment-pull-request@v2
        with:
          # Access the GITHUB_TOKEN token from secrets
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
            Hello world ! :wave:
